
\echo SRC_SCHEMA :SRC_SCHEMA
\echo DST_SCHEMA :DST_SCHEMA
\echo SKIP_AGENCY_ID_STRING :SKIP_AGENCY_ID_STRING 
\echo SKIP_TRIP_ID_STRING :SKIP_TRIP_ID_STRING 
\! set |grep ^PG

/*

\i print_settings.sql

*/
